[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["catalinapj <catalinadamian71@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
fastapi = ">=0.133.0,<0.134.0"
uvicorn = ">=0.41.0,<0.42.0"
sqlalchemy = ">=2.0.46,<3.0.0"
psycopg2-binary = ">=2.9.11,<3.0.0"
alembic = ">=1.18.4,<2.0.0"
pydantic = {extras = ["email"], version = "^2.12.5"}
passlib = ">=1.7.4"
bcrypt = "4.0.1"
python-multipart = "^0.0.22"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]
